name: publish doc to GitHub Page
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  publish:
    name: publish doc to GitHub Page
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Node environment for npm
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn build:doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
